default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tplhack_development
  host: localhost

test:
  <<: *default
  database: tplhack_test

production:
  <<: *default
  database: tplhack_production
  username: tplhack
  password: <%= ENV['TPLHACK_DATABASE_PASSWORD'] %>
