# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc5ae4884301a03635512b3841ce31c0639c8cce0d9d71450a8df04dc985d275075adc15eefd024c107e8a3fc14395d5b44bc8803fb6a554266b1ae77f643261

test:
  secret_key_base: 3e50f0cbfa35c2dadbe024715dd1acc3be081b33572f72c64a8838b10f326ad63325ad8046e6b7033f56b5e2292611115746a19c9c7a05c1f5881cc4c896168e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
